const fs=require('fs');
const R=(f,a,b)=>{let s=fs.readFileSync(f,'utf8');if(!s.includes(a)){console.log('MISS',f,a);return;}fs.writeFileSync(f,s.replace(a,b));};
R('h_sylphir.js',"when: { on: 'hit', who: 'other' }","when: { on: 'play', who: 'other', type: '공격' }");
R('h_sylphir.js',"다른 아군의 카드가 적을 치면 +1","다른 아군이 공격 카드를 내면 +1");
R('h_sylphir.js',"다른 아군이 적을 칠 때마다","다른 아군이 공격 카드를 낼 때마다");
R('h_netti.js',"O('신비한 광석', [sh(1.7)","O('신비한 광석', [sh(1.85)");
R('h_netti.js',"O('초정밀 탐사', [dig(2), sh(0.5)], { cost: 1 })","O('초정밀 탐사', [dig(2), sh(0.5)])");
R('h_daya.js',"O('보석 세공', [d(2.2)","O('보석 세공', [d(2.35)");
R('h_pureshine.js',"O('나의 아름다운 장미꽃에게', [sh(1.6)","O('나의 아름다운 장미꽃에게', [sh(1.85)");
R('h_pureshine.js',"O('빨개진 얼굴', [draw(1), st('사기', 1), ...FIRST], { cost: 1 })","O('빨개진 얼굴', [draw(1), st('사기', 1), ...FIRST], { tags: ['소멸'] })");
R('h_pureshine.js',"O('기다림 끝에 도착한 답장', [draw(1), make(FIN, 1)], { cost: 1 })","O('기다림 끝에 도착한 답장', [draw(1), make(FIN, 1)])");
R('h_rude.js',"O('용족 2인자의 의무', [sh(3.2)","O('용족 2인자의 의무', [sh(3.4)");
R('h_rude.js',"O('근손실 방지', [sh(2.8)","O('근손실 방지', [sh(3.1)");
R('h_rude.js',"O('노는 셈 치고', [dDef(0.5), ifS(KW, 1)","O('노는 셈 치고', [dDef(0.6), ifS(KW, 1)");
R('h_ritz.js',"O('한 걸음 밀기', [dAll(0.7)","O('한 걸음 밀기', [dAll(0.75)");
R('h_sylvia.js',"O('가벼운 유희', [sh(1.6), st('반격', 1)]","O('가벼운 유희', [sh(1.2), st('반격', 2)]");
R('h_sylvia.js',"O('은빛 무도회', [sh(3.0)","O('은빛 무도회', [sh(3.6)");
R('h_sylvia.js',"O('숙녀의 여흥', [sh(2.5)","O('숙녀의 여흥', [sh(2.8)");
R('h_sylphir.js',"O('날갯짓', [dRnd(0.5, 2)]","O('날갯짓', [dRnd(0.5, 3)]");
R('h_annette.js',"O('최강자는 아직', [CHAMP, draw(1), st('사기', 1)], { cost: 1 })","O('최강자는 아직', [CHAMP, draw(1), stk(CH, 2)])");
R('h_annette.js',"O('한 판 더', [CHAMP, draw(1)], { tags: ['보존'] })","O('한 판 더', [CHAMP, draw(1)], { tags: ['보존', '개전'] })");
R('h_aragnia.js',"O('여왕의 칙령', [dAll(0.7), st('약화', 1, 'allEnemies')])","O('여왕의 칙령', [dAll(0.8), st('약화', 1, 'allEnemies')])");
R('h_opal.js',"O('오팔 파편', [dRnd(0.6, 2)","O('오팔 파편', [dRnd(0.65, 2)");
R('h_jade.js',"O('광역 난방', [dAll(1.6)","O('광역 난방', [dAll(1.8)");
R('h_jade.js',"O('밑줄 그어 둔 곳', [draw(2), ...HOLD], { tags: ['보존', '개전'] })","O('밑줄 그어 둔 곳', [draw(2), st('다음 턴 드로우', 1), ...HOLD], { tags: ['보존'] })");
R('h_jade.js',"O('귀한 판본', [d(1.3)","O('귀한 판본', [d(1.55)");
R('h_jade.js',"O('비취 동전', [d(1.3)","O('비취 동전', [d(1.45)");
R('h_jade.js',"O('환불 불가', [d(2.4)","O('환불 불가', [d(2.8)");
R('h_kidian.js',"O('이중 찌르기', [d(0.5, { hits: 2 })","O('이중 찌르기', [d(0.6, { hits: 2 })");
R('h_kidian.js',"O('완벽한 해부', [tough(2), st('잔불', 1)], { cost: 1 })","O('완벽한 해부', [tough(2), st('잔불', 1)])");
R('h_kidian.js',"O('쿠나이 투척', [d(1.2), tough(1)]","O('쿠나이 투척', [d(1.3), tough(1)]");
R('h_kidian.js',"O('관통 쿠나이', [d(2.0)","O('관통 쿠나이', [d(2.1)");
R('h_kidian.js',"O('회수 쿠나이', [d(2.0)","O('회수 쿠나이', [d(2.2)");
R('h_pira.js',"O('황철석 가루', [dRnd(0.45, 3)","O('황철석 가루', [dRnd(0.5, 3)");
