import { E1, EA, ER, D, DD, SH, HL, ST, K, SP, DRAW, AP, TOUGH, F, up, cheap, keep, plus, O, B, BF, BT } from './lib.mjs';
import { atk1, atk2, shd, hel } from './heroes-a.mjs';

const ATKRUN = v => F('atkMod', { v, run: true, target: 'self' });
const LOAN = (sagi, weak) => F('later', { n: 2, then: [ST('약화', weak, EA), F('ifStack', { id: '빌려준 맛' }), F('dealtMod', { v: -0.2, target: 'allAllies', turns: 1 }), SP('빌려준 맛', 'all')] });

export const heroesB = [
// ─────────────────────────────────────────────── 시저
{
  hero: { id: '시저', name: '시저', nature: '냉정', row: 'mid', role: '서포터', star: 3, hp: 600, atk: 86, def: 60, crit: 5,
    blurb: '좋은 걸 맛보게 한 뒤 빼앗는 빌런 지망생. 사기를 빌려주고 두 턴 뒤 거둬 가며 적을 약하게 만든다 — 그 사이 적을 쓰러뜨리면 빚은 없던 일.',
    keyword: { name: '빌려준 맛', desc: '시저가 빌려준 사기 — 두 턴 뒤 거둬 간다(그 사이 처치하면 탕감)', carrier: 'self', cap: 4 },
    passives: [
      { name: '다 먹었으면 됐어', when: { on: 'kill' }, conds: [{ c: 'stack', id: '빌려준 맛', n: 1 }], fx: [SP('빌려준 맛', 'all')] },
    ],
    ult: { name: '가지치기', cost: 150, fx: [D(1.5, EA), ST('약화', 2, EA), ST('사기', 1)] } },
  starters: [atk1('싹둑'), hel('간식 나눠주기')],
  uniques: [
    { name: '한정판의 맛', type: '스킬', cost: 1, signature: true, fx: [ST('사기', 2), K('빌려준 맛', 2), LOAN(2, 2)],
      oracles: [
        O('특대 사이즈', [ST('사기', 3), K('빌려준 맛', 2), LOAN(3, 3)]),
        O('시식 코너', [ST('사기', 2), K('빌려준 맛', 2), LOAN(2, 2)], { cost: 0 }),
        O('이자 없는 대출', [ST('사기', 2), DRAW(1), LOAN(2, 2)]),
        O('기간 한정', [ST('사기', 2), K('빌려준 맛', 2), LOAN(2, 2)], { tags: ['보존'] }),
        O('맛보기 세트', [ST('사기', 2), K('빌려준 맛', 2), LOAN(2, 2)], { tags: ['개전'] }),
      ],
      blesses: [B('달콤한 유혹', 'draw'), B('발맞추기', 'ap'), BF('가지 하나 더', [ST('약화', 1, E1)])] },
    { name: '싹둑싹둑', type: '공격', cost: 1, fx: [D(1.2), ST('약화', 1, E1), F('ifKill'), ST('사기', 1)],
      oracles: [
        up('정원사의 가위', 1.35),
        O('가지 솎기', [D(0.8, EA), ST('약화', 1, EA), F('ifKill'), ST('사기', 1)]),
        O('뿌리째 싹둑', [D(1.4), ST('약화', 2, E1), F('ifKill'), ST('사기', 1)]),
        O('빠른 가위질', [D(1.0), ST('약화', 1, E1), F('ifKill'), ST('사기', 1)], { cost: 0 }),
        O('빌런의 미소', [D(1.2), ST('약화', 1, E1), F('ifKill'), AP(1)]),
      ],
      blesses: [B('잘 드는 가위', 'power'), B('가벼운 가위', 'cost'), B('서늘한 날', 'frost')] },
    { name: '빼앗는 재미', type: '스킬', cost: 1, fx: [ST('약화', 2, EA), SH(1.2)],
      oracles: [
        up('몽땅 빼앗기', 1.35),
        O('슬쩍 빼앗기', [ST('약화', 1, EA), SH(1.0)], { cost: 0 }),
        O('간식 회수', [ST('약화', 2, EA), SH(1.2), HL(0.8)]),
        O('빌런의 계약서', [ST('약화', 2, EA), SH(1.2), ST('손상', 1, EA)]),
        O('나눠 먹기', [ST('약화', 2, EA), SH(1.2), DRAW(1)]),
      ],
      blesses: [B('든든한 간식', 'guard'), B('얄미운 손', 'draw'), B('빠른 손', 'cost')] },
    { name: '빌런의 품격', type: '강화', cost: 1, fx: [ST('사기', 1), ST('약화', 1, EA)],
      oracles: [
        O('진정한 빌런', [ST('사기', 2), ST('약화', 1, EA)]),
        O('지망생의 품격', [ST('사기', 1), ST('약화', 1, EA)], { cost: 0 }),
        O('계획된 악행', [ST('사기', 1), ST('약화', 2, EA), K('빌려준 맛', 1)]),
        O('넉넉한 인심', [ST('사기', 1), ST('약화', 1, EA), ST('결의', 1)]),
        O('등장 연출', [ST('사기', 1), ST('약화', 2, EA)], { tags: ['개막'] }),
      ],
      blesses: [B('날 선 품격', 'atkUp'), B('여유', 'defUp'), B('짧은 대사', 'cost')] },
  ],
},
// ─────────────────────────────────────────────── 멜루나
{
  hero: { id: '멜루나', name: '멜루나', nature: '냉정', row: 'back', role: '서포터', star: 3, hp: 530, atk: 86, def: 58, crit: 5,
    blurb: '법의 빈틈으로 회사를 굴리는 멜론 회장. 이번 턴 AP 를 묻어 두면 두 턴 뒤 두 배로 돌아오고, 그 사이 적을 쓰러뜨리면 수익이 붙는다.',
    keyword: { name: '수익', desc: '투자하는 동안 처치로 붙은 이자 — 투자가 돌아올 때 AP 로 더 받는다', carrier: 'self', cap: 3 },
    passives: [
      { name: '이자 수익', when: { on: 'kill' }, limit: { per: 'turn', n: 1 }, fx: [K('수익', 1), DRAW(1)] },
    ],
    ult: { name: '멜론머스크 X', cost: 150, fx: [AP(2), DRAW(2), K('수익', 1)] } },
  starters: [atk1('멜론 씨 튕기기'), hel('멜론 한 조각')],
  uniques: [
    { name: '장기 투자', type: '스킬', cost: 1, signature: true,
      fx: [F('later', { n: 2, then: [AP(2), F('ifStack', { id: '수익' }), AP(1), SP('수익', 1)] }), ST('저장', 1), DRAW(1)],
      oracles: [
        O('우량주', [F('later', { n: 2, then: [AP(3), F('ifStack', { id: '수익' }), AP(1), SP('수익', 1)] }), ST('저장', 1)]),
        O('단타', [F('later', { n: 1, then: [AP(2), F('ifStack', { id: '수익' }), AP(1), SP('수익', 1)] }), ST('저장', 1)]),
        O('분산 투자', [F('later', { n: 2, then: [AP(2), DRAW(1), F('ifStack', { id: '수익' }), AP(1)] }), ST('저장', 1)]),
        O('적립식', [F('later', { n: 2, then: [AP(2), F('ifStack', { id: '수익' }), AP(1), SP('수익', 1)] }), ST('저장', 1), DRAW(1)]),
        O('선물 계약', [F('later', { n: 2, then: [AP(2), F('ifStack', { id: '수익' }), AP(1), SP('수익', 1)] }), ST('저장', 1)], { tags: ['보존'] }),
      ],
      blesses: [B('복리', 'draw'), BF('배당금', [K('수익', 1)]), BT('미리 산 주식', ['개전'])] },
    { name: '멜론 씨 기관총', type: '공격', cost: 1, fx: [D(0.4, E1, { hits: 3 }), F('ifKill'), K('수익', 1)],
      oracles: [
        up('씨 없는 멜론 없다', 1.35),
        O('흩뿌리기', [D(0.3, ER, { hits: 5 }), F('ifKill'), K('수익', 1)]),
        O('적대적 인수', [D(0.45, E1, { hits: 3 }), F('ifKill'), K('수익', 2)]),
        O('작은 씨앗', [D(0.3, E1, { hits: 3 }), F('ifKill'), K('수익', 1)], { cost: 0 }),
        O('정밀 사격', [D(0.4, E1, { hits: 3 }), TOUGH(1), F('ifKill'), K('수익', 1)]),
      ],
      blesses: [B('단단한 씨', 'power'), B('가벼운 씨', 'cost'), B('약점 분석', 'weakSpot')] },
    { name: '법의 빈틈', type: '스킬', cost: 0, fx: [ST('저장', 1), DRAW(1)],
      oracles: [
        O('절세', [ST('저장', 2), DRAW(1)]),
        O('회계 감사', [ST('저장', 1), DRAW(2)]),
        O('보험 가입', [ST('저장', 1), DRAW(1), SH(1.0)]),
        O('내부 정보', [ST('저장', 1), DRAW(1), K('수익', 1)]),
        O('사전 공시', [ST('저장', 1), DRAW(1)], { tags: ['개전'] }),
      ],
      blesses: [B('빠른 결재', 'draw'), B('특별 보너스', 'ap'), BF('멜론 한 입', [HL(0.4)])] },
    { name: '멜론머스크 그룹', type: '강화', cost: 1, fx: [ST('근면', 1), K('수익', 2), ST('저장', 2)],
      oracles: [
        O('대기업', [ST('근면', 1), K('수익', 3), ST('저장', 3)]),
        O('스타트업', [ST('근면', 1), K('수익', 2), ST('저장', 2)], { cost: 0 }),
        O('사내 복지', [ST('근면', 1), K('수익', 2), ST('불굴', 1)]),
        O('글로벌 진출', [ST('근면', 1), K('수익', 2), ST('사기', 1)]),
        O('창립 기념일', [ST('근면', 1), K('수익', 2), ST('저장', 2)], { tags: ['개막'] }),
      ],
      blesses: [B('회장님의 힘', 'atkUp'), B('튼튼한 금고', 'defUp'), B('구조 조정', 'cost')] },
  ],
},
// ─────────────────────────────────────────────── 이프리트
{
  hero: { id: '이프리트', name: '이프리트', nature: '광기', row: 'front', role: '딜러', star: 2, hp: 700, atk: 109, def: 38, crit: 10,
    blurb: '장작과 새까맣게 탄 음식을 좋아하는 불의 정령. 손패를 장작으로 태울수록 다음 일격이 뜨거워진다.',
    keyword: { name: '장작', desc: '태워 넣은 땔감 — 다음 공격 카드 한 장에 실린다', carrier: 'self', cap: 3, consumeAll: true, per: [{ stat: 'dealt', v: 0.3 }] },
    passives: [
      { name: '장작 넣기', when: { on: 'exhaust', who: 'any' }, limit: { per: 'turn', n: 3 }, fx: [K('장작', 1)] },
    ],
    ult: { name: '캠프파이어', cost: 200, fx: [D(1.5, EA), ST('고통', 4, EA), K('장작', 2)] } },
  starters: [atk1('불의 검 베기'), atk2('업화 대검 내려치기'), shd('열기 방벽', 1)],
  uniques: [
    { name: '땔감 던지기', type: '스킬', cost: 0, fx: [F('burn', { v: 1 }), DRAW(2)],
      oracles: [
        O('마른 장작', [F('burn', { v: 1 }), DRAW(2), ST('고통', 2, E1)]),
        O('장작 한 아름', [F('burn', { v: 2 }), DRAW(3)]),
        O('불쏘시개', [F('burn', { v: 1 }), DRAW(2), K('장작', 1)]),
        O('타닥타닥', [F('burn', { v: 1 }), DRAW(2), SH(0.8)]),
        O('미리 쌓은 장작', [F('burn', { v: 1 }), DRAW(2)], { tags: ['개전'] }),
      ],
      blesses: [B('바람 불기', 'draw'), B('부지깽이', 'ap'), BF('불티', [ST('고통', 1, E1)])] },
    { name: '새까만 대검', type: '공격', cost: 2, fx: [F('burn', { v: 2 }), D(2.2), ST('고통', 3, E1)],
      oracles: [
        up('숯이 된 대검', 1.35),
        cheap('그을린 검', 0.8),
        O('업화 휘두르기', [F('burn', { v: 2 }), D(1.2, EA), ST('고통', 2, EA)]),
        O('탄 냄새', [F('burn', { v: 2 }), D(2.2), ST('고통 각인', 1, E1)]),
        O('불기둥', [F('burn', { v: 2 }), D(2.4), TOUGH(1)]),
      ],
      blesses: [B('타오르는 날', 'power'), B('가벼운 칼집', 'cost'), B('뜨거운 약점', 'weakSpot')] },
    { name: '불꽃 베기', type: '공격', cost: 1, fx: [F('burn', { v: 1 }), D(1.2), ST('고통', 2, E1)],
      oracles: [
        up('화염 베기', 1.35),
        O('연속 베기', [F('burn', { v: 1 }), D(0.6, E1, { hits: 2 }), ST('고통', 3, E1)]),
        O('불똥 튀기기', [F('burn', { v: 1 }), D(0.8, EA), ST('고통', 1, EA)]),
        O('잿불', [F('burn', { v: 1 }), D(1.0), ST('고통', 2, E1)], { cost: 0 }),
        O('뜨거운 일격', [F('burn', { v: 1 }), D(1.3), ST('고통', 2, E1)], { tags: ['보존'] }),
      ],
      blesses: [B('센 불', 'power'), B('가벼운 손목', 'cost'), B('그을린 상처', 'frost')] },
    { name: '모닥불 피우기', type: '강화', cost: 1, fx: [ST('고통 각인', 1, EA), K('장작', 3)],
      oracles: [
        O('큰 모닥불', [ST('고통 각인', 2, EA), K('장작', 3)]),
        O('성냥 하나', [ST('고통 각인', 1, EA), K('장작', 3)], { cost: 0 }),
        O('불의 정령', [ST('고통 각인', 1, EA), K('장작', 3), ATKRUN(0.2)]),
        O('따뜻한 불가', [ST('고통 각인', 1, EA), K('장작', 3), ST('결정화', 1)]),
        O('미리 지핀 불', [ST('고통 각인', 1, EA), K('장작', 3)], { tags: ['개막'] }),
      ],
      blesses: [B('타오르는 힘', 'atkUp'), B('불꽃 갑옷', 'defUp'), B('마른 장작', 'cost')] },
  ],
},
// ─────────────────────────────────────────────── 우이
{
  hero: { id: '우이', name: '우이', nature: '활발', row: 'mid', role: '서포터', star: 3, hp: 660, atk: 86, def: 63, crit: 5,
    blurb: '견디기 힘든 걸 덮어 주는 이슬비 정령. 손에 든 싫은 카드를 비에 씻어 내고 개굴비를 남긴다 — 셋을 덮으면 파티의 아픔이 씻겨 간다.',
    keyword: { name: '외면', desc: '보슬비로 덮어 둔 싫은 것 — 셋이면 파티의 아픔이 씻겨 간다', carrier: 'self', cap: 3,
      rules: [{ name: '말하는 대로', when: { on: 'stackReach', id: '외면', n: 3 }, fx: [F('cleanse', { v: 2 }), HL(1.0), SP('외면', 'all')] }] },
    passives: [
      { name: '싫은 건 안 보면 돼', when: { on: 'drawn', who: 'any', type: '상태' }, limit: { per: 'turn', n: 2 }, fx: [F('make', { id: '우이_t1', v: 1 })] },
      { name: '에루의 우산', when: { on: 'exhaust' }, limit: { per: 'turn', n: 2 }, fx: [K('외면', 1)] },
    ],
    ult: { name: '말하는대로!', cost: 250, fx: [F('cleanse', { v: 3 }), HL(2.0), ST('면역', 1)] } },
  starters: [atk1('빗방울'), hel('보슬보슬')],
  tokens: [{ id: '우이_t1', name: '개굴비', cost: 0, type: '스킬', tags: ['소멸'], fx: [HL(0.8), DRAW(1)], blurb: '개구리 우산 아래로 내리는 다정한 비.' }],
  uniques: [
    { name: '보슬비로 덮기', type: '스킬', cost: 1, signature: true, fx: [F('burn', { v: 1 }), F('make', { id: '우이_t1', v: 1 }), F('cleanse', { v: 1 })],
      oracles: [
        O('장대비로 덮기', [F('burn', { v: 2 }), F('make', { id: '우이_t1', v: 2 }), F('cleanse', { v: 1 })]),
        O('이슬비', [F('burn', { v: 1 }), F('make', { id: '우이_t1', v: 1 }), F('cleanse', { v: 1 })], { cost: 0 }),
        O('빗소리', [F('burn', { v: 1 }), F('make', { id: '우이_t1', v: 1 }), SH(1.2)]),
        O('여우비', [F('burn', { v: 1 }), F('make', { id: '우이_t1', v: 1 }), F('cleanse', { v: 1 })], { tags: ['보존'] }),
        O('무지개', [F('burn', { v: 1 }), F('make', { id: '우이_t1', v: 1 }), HL(1.0)]),
      ],
      blesses: [B('촉촉한 땅', 'heal'), B('빗방울 소리', 'draw'), B('작은 구름', 'cost')] },
    { name: '소나기', type: '공격', cost: 1, fx: [D(0.45, ER, { hits: 3 }), K('외면', 1)],
      oracles: [
        up('여름 소나기', 1.35),
        O('우박', [D(0.5, ER, { hits: 3 }), ST('약화', 1, ER), K('외면', 1)]),
        O('빗줄기', [D(1.4), K('외면', 1)]),
        O('보슬비 한 줌', [D(0.35, ER, { hits: 3 }), K('외면', 1)], { cost: 0 }),
        O('물웅덩이 첨벙', [D(0.45, ER, { hits: 3 }), K('외면', 1), HL(0.6)]),
      ],
      blesses: [B('굵은 빗방울', 'power'), B('가벼운 구름', 'cost'), B('차가운 비', 'frost')] },
    { name: '모른 척', type: '스킬', cost: 0, fx: [F('cleanse', { v: 1 }), DRAW(1), K('외면', 1)],
      oracles: [
        O('못 본 척', [F('cleanse', { v: 2 }), DRAW(1), K('외면', 1)]),
        O('딴청', [F('cleanse', { v: 1 }), DRAW(2), K('외면', 1)]),
        O('우산 쓰기', [F('cleanse', { v: 1 }), SH(1.0), K('외면', 1)]),
        O('콧노래', [F('cleanse', { v: 1 }), DRAW(1), K('외면', 2)]),
        O('흐린 날', [F('cleanse', { v: 1 }), DRAW(1), K('외면', 1)], { tags: ['보존'] }),
      ],
      blesses: [B('맑게 갠 하늘', 'draw'), B('물장구', 'ap'), BF('이슬', [HL(0.4)])] },
    { name: '개굴개굴 합창', type: '강화', cost: 1, fx: [F('make', { id: '우이_t1', v: 2 }), ST('면역', 1)],
      oracles: [
        O('개구리 합창단', [F('make', { id: '우이_t1', v: 3 }), ST('면역', 1)]),
        O('작은 개구리', [F('make', { id: '우이_t1', v: 1 }), ST('면역', 1)], { cost: 0 }),
        O('에루와 함께', [F('make', { id: '우이_t1', v: 2 }), ST('면역', 2)]),
        O('장마철', [F('make', { id: '우이_t1', v: 2 }), ST('면역', 1), ST('초재생', 1)]),
        O('비 오는 아침', [F('make', { id: '우이_t1', v: 2 }), ST('면역', 1)], { tags: ['개막'] }),
      ],
      blesses: [B('신나는 노래', 'atkUp'), B('개구리 우비', 'defUp'), B('짧은 노래', 'cost')] },
  ],
},
// ─────────────────────────────────────────────── 미로
{
  hero: { id: '미로', name: '미로', nature: '활발', row: 'front', role: '탱커', star: 3, hp: 1000, atk: 75, def: 76, crit: 5,
    blurb: '거울 속에서 지켜보며 응원하는 정령. 파티를 친 적에게 시선을 꽂아 그 적의 공격을 무디게 하고, 시선이 쌓인 적일수록 거울 조각이 깊이 박힌다.',
    keyword: { name: '시선', desc: '거울 속에서 지켜보는 눈 — 맞을 때마다 그 적에게 하나', carrier: 'enemy', cap: 3, per: [{ stat: 'dealt', v: -0.1 }] },
    passives: [
      { name: '지켜보고 있어요', when: { on: 'hurt', guarded: true }, fx: [K('시선', 1, E1)] },
    ],
    ult: { name: '수많은 시선', cost: 200, fx: [K('시선', 3, EA), SH(2.5), ST('반격', 2)] } },
  starters: [atk1('거울 조각'), shd('거울 뒤로')],
  uniques: [
    { name: '거울 반사', type: '공격', cost: 1, signature: true, fx: [DD(0.6), F('perStack', { id: '시선' }), DD(0.3)],
      oracles: [
        O('맑은 거울', [DD(0.8), F('perStack', { id: '시선' }), DD(0.4)]),
        O('손거울', [DD(0.5), F('perStack', { id: '시선' }), DD(0.25)], { cost: 0 }),
        O('반사광', [DD(0.6), F('perStack', { id: '시선' }), DD(0.3), SH(1.0)]),
        O('되비추기', [DD(0.6), F('perStack', { id: '시선' }), DD(0.3), ST('약화', 1, E1)]),
        O('뚫어지게 보기', [DD(0.6), K('시선', 1, E1), F('perStack', { id: '시선' }), DD(0.3)]),
      ],
      blesses: [B('반짝이는 거울', 'power'), B('가벼운 거울', 'cost'), B('눈부심', 'frost')] },
    { name: '거울 속으로', type: '스킬', cost: 1, fx: [SH(2.2), ST('반격', 1)],
      oracles: [
        up('전신 거울', 1.35),
        O('거울 방', [SH(2.2), ST('반격', 2)]),
        O('거울 너머', [SH(1.8), ST('반격', 1)], { cost: 0 }),
        O('응원 메시지', [SH(2.2), ST('반격', 1), ST('사기', 1)]),
        O('지켜 줄게요', [SH(2.4), ST('반격', 1), ST('피해 감소', 1)]),
      ],
      blesses: [B('두꺼운 유리', 'guard'), B('거울 닦기', 'draw'), B('가벼운 틀', 'cost')] },
    { name: '수많은 눈', type: '스킬', cost: 1, fx: [K('시선', 1, EA), SH(1.5)],
      oracles: [
        O('빤히 보기', [K('시선', 2, EA), SH(1.5)]),
        O('흘깃', [K('시선', 1, EA), SH(1.2)], { cost: 0 }),
        O('거울 미로', [K('시선', 1, EA), SH(1.5), ST('약화', 1, EA)]),
        O('눈 맞춤', [K('시선', 1, EA), SH(1.5), DRAW(1)]),
        O('밤새 지켜보기', [K('시선', 1, EA), SH(1.8)], { tags: ['보존'] }),
      ],
      blesses: [B('든든한 눈', 'guard'), B('깜빡', 'draw'), B('살짝 보기', 'cost')] },
    { name: '깨진 거울 조각', type: '공격', cost: 2, fx: [DD(0.7, EA), ST('약화', 1, EA)],
      oracles: [
        up('산산조각', 1.35),
        cheap('작은 파편', 0.8),
        O('파편 비', [DD(0.7, EA), ST('약화', 1, EA), K('시선', 1, EA)]),
        O('날카로운 파편', [DD(0.7, EA), ST('약화', 1, EA), ST('손상', 1, EA)]),
        O('거울 방패', [DD(0.7, EA), ST('약화', 1, EA), SH(1.2)]),
      ],
      blesses: [B('날 선 조각', 'power'), B('얇은 거울', 'cost'), B('반사된 빛', 'weakSpot')] },
  ],
},
// ─────────────────────────────────────────────── 아르코
{
  hero: { id: '아르코', name: '아르코', nature: '활발', row: 'mid', role: '딜러', star: 3, hp: 720, atk: 135, def: 28, crit: 10,
    blurb: '춤밖에 모르는 적포도 스트리트 댄서. 같은 결의 카드를 잇달아 이으면 스텝이 쌓이고, 세 번째 스텝에 브레이크가 터진다.',
    keyword: { name: '스텝', desc: '박자에 맞춰 밟은 스텝 — 셋이면 브레이크', carrier: 'self', cap: 3,
      rules: [{ name: '브레이크', when: { on: 'stackReach', id: '스텝', n: 3 }, fx: [D(0.6, E1, { hits: 2 }), AP(1), SP('스텝', 'all')] }] },
    passives: [
      { name: '댄스배틀', when: { on: 'play', type: '공격' }, conds: [{ c: 'playedMin', n: 3 }], limit: { per: 'turn', n: 1 }, fx: [K('스텝', 1)] },
    ],
    ult: { name: '퍼플 쇼츠', cost: 250, fx: [D(0.5, ER, { hits: 4 }), K('스텝', 2)] } },
  starters: [atk1('스텝 킥'), atk2('토네이도 킥'), shd('백스핀 회피', 1)],
  uniques: [
    { name: '웨이브 킥', type: '공격', cost: 1, signature: true, fx: [D(1.2), F('ifChain'), K('스텝', 1)],
      oracles: [
        up('파도 타기', 1.35),
        O('투스텝', [D(1.2), F('ifChain'), K('스텝', 2)]),
        O('토프록', [D(1.0), F('ifChain'), K('스텝', 1)], { cost: 0 }),
        O('윈드밀', [D(0.8, EA), F('ifChain'), K('스텝', 1)]),
        O('프리즈 킥', [D(1.2), TOUGH(1), F('ifChain'), K('스텝', 1)]),
      ],
      blesses: [B('강한 박자', 'power'), B('가벼운 스텝', 'cost'), B('약점 킥', 'weakSpot')] },
    { name: '토네이도 스핀', type: '공격', cost: 2, fx: [D(1.0, EA), F('ifChain'), K('스텝', 2)],
      oracles: [
        up('헤드스핀', 1.35),
        cheap('백스핀', 0.8),
        O('에어 트랙', [D(1.0, EA), ST('약화', 1, EA), F('ifChain'), K('스텝', 2)]),
        O('나이키', [D(2.4), F('ifChain'), K('스텝', 2)]),
        O('플레어', [D(0.55, EA, { hits: 2 }), F('ifChain'), K('스텝', 2)]),
      ],
      blesses: [B('회오리', 'power'), B('가벼운 회전', 'cost'), B('어지러운 바람', 'frost')] },
    { name: '프리즈', type: '스킬', cost: 0, fx: [K('스텝', 1), DRAW(1)],
      oracles: [
        O('베이비 프리즈', [K('스텝', 1), DRAW(2)]),
        O('체어 프리즈', [K('스텝', 1), DRAW(1), SH(1.0)]),
        O('에어 체어', [K('스텝', 2), DRAW(1)]),
        O('포즈!', [K('스텝', 1), DRAW(1), ST('사기', 1)]),
        O('무대 인사', [K('스텝', 1), DRAW(1)], { tags: ['개전'] }),
      ],
      blesses: [B('리듬 타기', 'draw'), B('비트 넘기기', 'ap'), BT('준비 자세', ['개전'])] },
    { name: '적포도 스트리트', type: '강화', cost: 1, fx: [ST('잔광', 2), K('스텝', 1), ATKRUN(0.15)],
      oracles: [
        O('메인 스테이지', [ST('잔광', 3), K('스텝', 1), ATKRUN(0.2)]),
        O('골목 무대', [ST('잔광', 2), K('스텝', 1), ATKRUN(0.15)], { cost: 0 }),
        O('관객 호응', [ST('잔광', 2), K('스텝', 1), ST('사기', 1)]),
        O('크루 결성', [ST('잔광', 2), K('스텝', 1), ST('협공', 2)]),
        O('오프닝 댄스', [ST('잔광', 2), K('스텝', 2), ATKRUN(0.15)], { tags: ['개전'] }),
      ],
      blesses: [B('보랏빛 열정', 'atkUp'), B('유연한 몸', 'defUp'), B('가벼운 신발', 'cost')] },
  ],
},
// ─────────────────────────────────────────────── 쥬비
{
  hero: { id: '쥬비', name: '쥬비', nature: '활발', row: 'mid', role: '딜러', star: 2, hp: 550, atk: 115, def: 27, crit: 10,
    blurb: '하나의 정신을 나눠 쓰는 꿀벌 군집. 턴마다 벌이 모여들어 쥬비의 공격을 따라 쏘고, 파티가 다치면 벌이 흩어진다.',
    keyword: { name: '벌', desc: '쥬비를 따라다니는 꿀벌 떼 — 공격 카드를 내면 마리 수만큼 쏜다', carrier: 'self', cap: 8,
      rules: [
        { name: '꿀 도둑 처단', when: { on: 'kill', mine: true }, fx: [K('벌', 2)] },
        { name: '흩어지는 벌', when: { on: 'hurt' }, limit: { per: 'turn', n: 1 }, fx: [SP('벌', 1)] },
        { name: '벌집 출발', when: { on: 'fightStart' }, fx: [K('벌', 2)] },
      ] },
    passives: [
      { name: '윙윙 집합', when: { on: 'turnStart' }, fx: [K('벌', 1)] },
      { name: '벌떼 습격', when: { on: 'play', type: '공격' }, fx: [F('perStack', { id: '벌' }), D(0.3, E1)] },
    ],
    ult: { name: '행복했쮸비', cost: 200, fx: [K('벌', 4), F('perStack', { id: '벌' }), D(0.2, EA)] } },
  starters: [atk1('벌침'), atk2('대장 벌침'), shd('밀랍 벽', 1)],
  uniques: [
    { name: '벌침 연타', type: '공격', cost: 1, signature: true, fx: [D(0.35, E1, { hits: 3 }), K('벌', 1)],
      oracles: [
        up('독침 연타', 1.35),
        O('일벌의 침', [D(0.35, E1, { hits: 3 }), K('벌', 2)]),
        O('가벼운 침', [D(0.3, E1, { hits: 3 }), K('벌', 1)], { cost: 0 }),
        O('흩뿌린 침', [D(0.3, ER, { hits: 4 }), K('벌', 1)]),
        O('꿀 도둑 표시', [D(0.35, E1, { hits: 3 }), ST('취약', 1, E1), K('벌', 1)]),
      ],
      blesses: [B('날카로운 침', 'power'), B('가벼운 날개', 'cost'), B('급소 찌르기', 'weakSpot')] },
    { name: '여왕벌 호출', type: '스킬', cost: 1, fx: [K('벌', 3), ST('협공', 1)],
      oracles: [
        O('대군단', [K('벌', 4), ST('협공', 1)]),
        O('정찰벌', [K('벌', 2), ST('협공', 1)], { cost: 0 }),
        O('밀랍 방패', [K('벌', 3), ST('협공', 1), SH(1.2)]),
        O('합창 윙윙', [K('벌', 3), ST('협공', 2)]),
        O('벌집 깨우기', [K('벌', 3), ST('협공', 1)], { tags: ['개전'] }),
      ],
      blesses: [B('윙윙 소리', 'draw'), B('날갯짓', 'ap'), B('꿀 한 방울', 'heal')] },
    { name: '벌떼 돌격', type: '공격', cost: 1, fx: [F('perStack', { id: '벌' }), D(0.25), SP('벌', 3)],
      oracles: [
        O('벌떼 폭풍', [F('perStack', { id: '벌' }), D(0.32), SP('벌', 3)]),
        O('작은 돌격', [F('perStack', { id: '벌' }), D(0.2), SP('벌', 3)], { cost: 0 }),
        O('벌떼 휘몰이', [F('perStack', { id: '벌' }), D(0.15, EA), SP('벌', 3)]),
        O('아끼는 벌', [F('perStack', { id: '벌' }), D(0.25), SP('벌', 2)]),
        O('꿀 도둑은 안 잊어', [F('perStack', { id: '벌' }), D(0.25), SP('벌', 3), ST('약화', 1, E1)]),
      ],
      blesses: [B('성난 벌떼', 'power'), B('빠른 날개', 'cost'), B('벌침 독', 'frost')] },
    { name: '밀랍 둥지', type: '강화', cost: 1, fx: [K('벌', 4), ATKRUN(0.15)],
      oracles: [
        O('거대한 벌집', [K('벌', 6), ATKRUN(0.15)]),
        O('작은 벌집', [K('벌', 4), ATKRUN(0.15)], { cost: 0 }),
        O('꿀 창고', [K('벌', 4), ATKRUN(0.15), ST('결의', 1)]),
        O('여왕의 축복', [K('벌', 4), ATKRUN(0.25)]),
        O('봄의 벌집', [K('벌', 4), ATKRUN(0.15)], { tags: ['개막'] }),
      ],
      blesses: [B('꿀 먹은 힘', 'atkUp'), B('밀랍 갑옷', 'defUp'), B('가벼운 벌집', 'cost')] },
  ],
},
// ─────────────────────────────────────────────── 오로라
{
  hero: { id: '오로라', name: '오로라', nature: '우울', row: 'front', role: '탱커', star: 3, hp: 900, atk: 75, def: 70, crit: 5,
    blurb: '혼자 남겨지는 걸 두려워하는 다정한 방패. 아군이 카드를 낼 때마다 빛무리가 짙어지고, 셋이 함께 움직인 턴엔 극광이 한 겹 더 내려앉는다.',
    keyword: { name: '빛무리', desc: '곁에 있는 이들이 남긴 빛 — 쌓일수록 실드가 두꺼워진다', carrier: 'self', cap: 3, per: [{ stat: 'guard', v: 0.15 }] },
    passives: [
      { name: '혼자 두지 않아', when: { on: 'play', who: 'other' }, limit: { per: 'turn', n: 2 }, fx: [K('빛무리', 1)] },
      { name: '외롭지 않게', when: { on: 'turnStart' }, conds: [{ c: 'stack', id: '빛무리', n: 3 }], fx: [DRAW(1), SH(0.6), SP('빛무리', 1)] },
    ],
    ult: { name: '고요한 빛무리', cost: 250, fx: [SH(3.0), ST('실드 보존', 1), DRAW(2)] } },
  starters: [atk1('빛 조각'), shd('극광 장막')],
  uniques: [
    { name: '오로라 커튼', type: '스킬', cost: 1, signature: true, fx: [SH(2.0), K('빛무리', 1), F('ifAllHeroes'), SH(1.0)],
      oracles: [
        O('극광의 밤', [SH(2.4), K('빛무리', 1), F('ifAllHeroes'), SH(1.4)]),
        O('엷은 빛', [SH(1.6), K('빛무리', 1), F('ifAllHeroes'), SH(0.8)], { cost: 0 }),
        O('빛의 고리', [SH(2.0), K('빛무리', 2), F('ifAllHeroes'), SH(1.0)]),
        O('함께하는 빛', [SH(2.0), K('빛무리', 1), F('ifAllHeroes'), ST('실드 유지', 1)]),
        O('기다리는 빛', [SH(2.2), K('빛무리', 1), F('ifAllHeroes'), SH(1.0)], { tags: ['보존'] }),
      ],
      blesses: [B('두터운 장막', 'guard'), B('나란히', 'draw'), B('가벼운 빛', 'cost')] },
    { name: '다정한 방패', type: '스킬', cost: 1, fx: [SH(1.6), ST('피해 감소', 1), F('ifAllHeroes'), DRAW(1)],
      oracles: [
        up('굳센 방패', 1.35),
        O('손잡기', [SH(1.6), ST('피해 감소', 2), F('ifAllHeroes'), DRAW(1)]),
        O('작은 방패', [SH(1.3), ST('피해 감소', 1), F('ifAllHeroes'), DRAW(1)], { cost: 0 }),
        O('곁에 있을게', [SH(1.6), ST('피해 감소', 1), F('ifAllHeroes'), AP(1)]),
        O('따뜻한 품', [SH(1.6), ST('피해 감소', 1), F('ifAllHeroes'), HL(1.0)]),
      ],
      blesses: [B('든든한 방패', 'guard'), B('어깨 기대기', 'heal'), B('나란히 걷기', 'ap')] },
    { name: '빛 조각 흩뿌리기', type: '공격', cost: 1, fx: [DD(0.6, EA), F('ifAllHeroes'), ST('결의', 1)],
      oracles: [
        up('별빛 흩뿌리기', 1.35),
        O('빛 화살', [DD(1.2), F('ifAllHeroes'), ST('결의', 1)]),
        O('반짝임', [DD(0.5, EA), F('ifAllHeroes'), ST('결의', 1)], { cost: 0 }),
        O('눈부신 빛', [DD(0.6, EA), ST('약화', 1, EA), F('ifAllHeroes'), ST('결의', 1)]),
        O('밤하늘', [DD(0.6, EA), K('빛무리', 1), F('ifAllHeroes'), ST('결의', 1)]),
      ],
      blesses: [B('밝은 빛', 'power'), B('가벼운 빛살', 'cost'), B('차가운 극광', 'frost')] },
    { name: '함께 있는 밤', type: '강화', cost: 1, fx: [ST('결정화', 2), K('빛무리', 3)],
      oracles: [
        O('긴긴 밤', [ST('결정화', 3), K('빛무리', 3)]),
        O('짧은 밤', [ST('결정화', 2), K('빛무리', 3)], { cost: 0 }),
        O('지켜 주는 밤', [ST('결정화', 2), K('빛무리', 3), ST('불굴', 1)]),
        O('모닥불 곁', [ST('결정화', 2), K('빛무리', 3), ST('반격', 2)]),
        O('해 질 녘', [ST('결정화', 2), K('빛무리', 3)], { tags: ['개막'] }),
      ],
      blesses: [B('빛나는 마음', 'defUp'), B('용기', 'atkUp'), B('짧은 기도', 'cost')] },
  ],
},
// ─────────────────────────────────────────────── 블랑셰
{
  hero: { id: '블랑셰', name: '블랑셰', nature: '우울', row: 'mid', role: '딜러', star: 3, hp: 650, atk: 125, def: 28, crit: 15,
    blurb: '감정 대신 머리의 장미가 빛나는 배우. 공격할 때마다 푸른 장미가, 약점을 찌를 때마다 붉은 장미가 피고, 두 빛깔이 다 피면 커튼콜이 올라온다.',
    keywords: [
      { name: '붉은 장미', desc: '약점을 찌른 연기에 피는 장미 — 푸른 장미와 둘씩이면 커튼콜', carrier: 'self', cap: 2,
        rules: [{ name: '커튼콜', when: { on: 'stackReach', id: '붉은 장미', n: 2 }, conds: [{ c: 'stack', id: '푸른 장미', n: 2 }], fx: [SP('붉은 장미', 'all'), SP('푸른 장미', 'all'), F('make', { id: '블랑셰_t1', v: 1 })] }] },
      { name: '푸른 장미', desc: '담담한 연기에 피는 장미 — 붉은 장미와 둘씩이면 커튼콜', carrier: 'self', cap: 2,
        rules: [{ name: '커튼콜', when: { on: 'stackReach', id: '푸른 장미', n: 2 }, conds: [{ c: 'stack', id: '붉은 장미', n: 2 }], fx: [SP('붉은 장미', 'all'), SP('푸른 장미', 'all'), F('make', { id: '블랑셰_t1', v: 1 })] }] },
    ],
    passives: [
      { name: '두 빛깔 장미', when: { on: 'play', type: '공격' }, fx: [K('푸른 장미', 1)] },
    ],
    ult: { name: '파랑새 정원', cost: 200, fx: [D(1.2, EA), F('make', { id: '블랑셰_t1', v: 1 }), K('붉은 장미', 1)] } },
  starters: [atk1('장미 가시'), atk2('가시 장미 다발'), shd('꽃잎 커튼', 1)],
  tokens: [{ id: '블랑셰_t1', name: '커튼콜', cost: 0, type: '공격', tags: ['소멸'], fx: [D(1.0, EA), ST('사기', 1)], blurb: '두 빛깔 장미가 다 핀 무대의 마지막 인사.' }],
  uniques: [
    { name: '붉은 장미 가시', type: '공격', cost: 1, tags: ['약점 공격'], signature: true, fx: [D(1.2), K('붉은 장미', 1)],
      oracles: [
        up('핏빛 장미', 1.35),
        O('가시덤불', [D(0.7, EA), K('붉은 장미', 1)], { tags: ['약점 공격'] }),
        O('장미 한 송이', [D(1.0), K('붉은 장미', 1)], { cost: 0, tags: ['약점 공격'] }),
        O('독 가시', [D(1.2), ST('취약', 1, E1), K('붉은 장미', 1)], { tags: ['약점 공격'] }),
        O('열연', [D(1.2), K('붉은 장미', 2)], { tags: ['약점 공격'] }),
      ],
      blesses: [B('짙은 향기', 'power'), B('가벼운 줄기', 'cost'), B('약점 연기', 'weakSpot')] },
    { name: '장미 정원 산책', type: '공격', cost: 2, tags: ['약점 공격'], fx: [D(0.8, EA), K('붉은 장미', 1)],
      oracles: [
        up('만개한 정원', 1.35),
        cheap('작은 화단', 0.8),
        O('가시 울타리', [D(0.8, EA), SH(1.0), K('붉은 장미', 1)], { tags: ['약점 공격'] }),
        O('꽃잎 폭풍', [D(0.5, EA, { hits: 2 }), K('붉은 장미', 1)], { tags: ['약점 공격'] }),
        O('파랑새의 정원', [D(0.8, EA), K('붉은 장미', 1), K('푸른 장미', 1)], { tags: ['약점 공격'] }),
      ],
      blesses: [B('향기로운 바람', 'power'), B('산책로', 'cost'), B('서리 내린 장미', 'frost')] },
    { name: '앙코르', type: '스킬', cost: 0, fx: [K('붉은 장미', 1), K('푸른 장미', 1), DRAW(1)],
      oracles: [
        O('기립 박수', [K('붉은 장미', 1), K('푸른 장미', 1), DRAW(2)]),
        O('무대 인사', [K('붉은 장미', 1), K('푸른 장미', 1), SH(1.0)]),
        O('한 번 더', [K('붉은 장미', 1), K('푸른 장미', 1), ST('사기', 1)]),
        O('커튼 뒤에서', [K('붉은 장미', 1), K('푸른 장미', 1), DRAW(1)], { tags: ['보존'] }),
        O('리허설', [K('붉은 장미', 1), K('푸른 장미', 1), DRAW(1)], { tags: ['개전'] }),
      ],
      blesses: [B('관객의 환호', 'draw'), B('조명 켜기', 'ap'), BT('예고편', ['개전'])] },
    { name: '무대 위의 배우', type: '강화', cost: 1, fx: [F('critMod', { v: 0.15, run: true, target: 'self' }), ST('사기', 1)],
      oracles: [
        O('주연 배우', [F('critMod', { v: 0.2, run: true, target: 'self' }), ST('사기', 2)]),
        O('단역', [F('critMod', { v: 0.15, run: true, target: 'self' }), ST('사기', 1)], { cost: 0 }),
        O('명연기', [F('critMod', { v: 0.15, run: true, target: 'self' }), ST('사기', 1), ATKRUN(0.15)]),
        O('빛나는 장미', [F('critMod', { v: 0.15, run: true, target: 'self' }), ST('사기', 1), K('붉은 장미', 2)]),
        O('막이 오르면', [F('critMod', { v: 0.15, run: true, target: 'self' }), ST('사기', 1)], { tags: ['개막'] }),
      ],
      blesses: [B('무대 체질', 'atkUp'), B('의상', 'defUp'), B('짧은 독백', 'cost')] },
  ],
},
];
