import { E1, EA, ER, D, DD, SH, HL, ST, K, SP, DRAW, AP, TOUGH, F, up, cheap, keep, plus, O, B, BF, BT } from './lib.mjs';

export const atk1 = (name, n = 2) => ({ name, type: '공격', cost: 1, fx: [D(1.0)], n });
export const atk2 = name => ({ name, type: '공격', cost: 2, fx: [D(2.2)], n: 1 });
export const shd = (name, n = 2) => ({ name, type: '스킬', cost: 1, fx: [SH(1.5)], n });
export const hel = (name, n = 2) => ({ name, type: '스킬', cost: 1, fx: [HL(1.2)], n });

export const heroesA = [
// ─────────────────────────────────────────────── 라이카
{
  hero: { id: '라이카', name: '라이카', nature: '순수', row: 'front', role: '딜러', star: 3, hp: 830, atk: 137, def: 40, crit: 10,
    blurb: '220V 콘센트를 사랑하는 번개 정령. 주먹을 내지를 때마다 제 몸에 전류를 꽂아 다음 주먹을 무겁게 한다 — 그 값은 파티 HP 로 치른다.',
    keyword: { name: '과충전', desc: '제 몸에 꽂은 220V — 다음 공격 카드 한 장이 무거워진다', carrier: 'self', cap: 1, consumeAll: true,
      per: [{ stat: 'dealt', v: 0.5 }] },
    passives: [
      { name: '220V 과충전', when: { on: 'play', type: '공격' }, conds: [{ c: 'hpMin', pct: 0.3 }], limit: { per: 'turn', n: 2 },
        fx: [F('payHpPct', { v: 0.02 }), K('과충전', 1), ST('충격', 1, E1)] },
    ],
    ult: { name: '원격 충전!!', cost: 200, fx: [D(1.6, EA), ST('충격', 2, EA), K('과충전', 1)] } },
  starters: [atk1('찌릿 펀치'), atk2('콰지직 펀치'), shd('정전기 가드', 1)],
  uniques: [
    { name: '급속 충전!', type: '스킬', cost: 1, signature: true, fx: [F('payHpPct', { v: 0.03 }), AP(1), K('과충전', 1)],
      oracles: [
        O('220V 직결', [F('payHpPct', { v: 0.03 }), AP(1), K('과충전', 1)], { cost: 0 }),
        O('카페 콘센트', [AP(1), K('과충전', 1), DRAW(1)]),
        O('전열은 맡겨', [AP(1), K('과충전', 1), SH(1.5)]),
        O('피뢰침', [F('payHpPct', { v: 0.03 }), AP(1), K('과충전', 1)], { tags: ['보존', '개전'] }),
        O('스파크 튀기기', [F('payHpPct', { v: 0.03 }), AP(1), ST('충격', 2, E1)]),
      ],
      blesses: [B('터보 배터리', 'draw'), BT('콘센트 찾기', ['개전']), BF('자부심의 스파크', [ST('충격', 1, E1)])] },
    { name: '감전 질주', type: '공격', cost: 2, fx: [D(1.3, EA), ST('충격', 1, EA), TOUGH(1, EA)],
      oracles: [
        up('질주 본능', 1.35),
        cheap('맨발 질주', 0.8),
        plus('번개 꼬리', [], 1.15),
        O('풀 스로틀', [D(2.0, EA), ST('충격', 2, EA), TOUGH(2, EA)], { cost: 3 }),
        O('고압선', [D(1.5, EA), ST('충격', 2, EA), TOUGH(1, EA)]),
      ],
      blesses: [B('불타는 질주', 'power'), B('가벼운 운동화', 'cost'), B('정전기 머리', 'frost')] },
    { name: '220V 스트레이트', type: '공격', cost: 1, fx: [D(1.4), TOUGH(1), F('ifBreak'), AP(1)],
      oracles: [
        up('380V 스트레이트', 1.35),
        O('어퍼컷', [D(1.6), TOUGH(1), F('ifBreak'), AP(2)]),
        O('번개 주먹', [D(1.6), ST('충격', 1, E1), F('ifBreak'), AP(1)]),
        O('한 방 더', [D(1.2), TOUGH(1), F('ifBreak'), AP(1)], { cost: 0 }),
        keep('참는 주먹', 1.25),
      ],
      blesses: [B('무거운 주먹', 'power'), B('약점 감전', 'weakSpot'), BF('흐르는 전류', [ST('충격', 1, E1)])] },
    { name: '자가 발전', type: '강화', cost: 1, fx: [ST('집중', 1), F('atkMod', { v: 0.2, run: true, target: 'self' }), K('과충전', 1)],
      oracles: [
        O('발전소 사고', [ST('집중', 1), F('atkMod', { v: 0.3, run: true, target: 'self' }), K('과충전', 1)]),
        O('예비 발전기', [ST('집중', 1), F('atkMod', { v: 0.2, run: true, target: 'self' }), K('과충전', 1)], { cost: 0 }),
        O('충전 완료', [ST('집중', 1), F('atkMod', { v: 0.2, run: true, target: 'self' }), ST('피해 감소', 2)]),
        O('전기 갑옷', [ST('집중', 1), F('atkMod', { v: 0.2, run: true, target: 'self' }), ST('불굴', 1)]),
        O('기다렸다는 듯', [ST('집중', 1), F('atkMod', { v: 0.25, run: true, target: 'self' }), K('과충전', 1)], { tags: ['개전'] }),
      ],
      blesses: [B('스스로 빛나기', 'atkUp'), B('얕은 잠', 'cost'), B('튼튼한 몸', 'defUp')] },
  ],
},
// ─────────────────────────────────────────────── 나이아
{
  hero: { id: '나이아', name: '나이아', nature: '순수', row: 'mid', role: '서포터', star: 3, hp: 600, atk: 75, def: 60, crit: 5,
    blurb: '인사 대신 물총부터 쏘는 외로운 수문장. 물총을 맞은 아군이 이번 턴 카드를 내면 물줄기나 물보라가 따라붙는다.',
    keywords: [{ name: '물총', desc: '나이아가 쏜 물에 젖은 아군 — 이번 턴 그 아군이 카드를 내면 물이 따라간다', carrier: 'hero', cap: 1, endClear: true }],
    passives: [
      { name: '물줄기', when: { on: 'play', marked: '물총', type: '공격' }, limit: { per: 'turn', n: 2 }, fx: [F('extra', { ratio: 0.6, target: E1 })] },
      { name: '물보라', when: { on: 'play', marked: '물총', type: '스킬' }, limit: { per: 'turn', n: 2 }, fx: [SH(0.6)] },
    ],
    ult: { name: '물의 세례를 받아라!', cost: 150, fx: [HL(1.5), SH(1.5), K('물총', 1, 'allAllies')] } },
  starters: [atk1('물방울'), hel('물 뿌리기')],
  uniques: [
    { name: '같이 놀자!', type: '스킬', cost: 0, signature: true, fx: [K('물총', 1, 'oneAlly'), DRAW(1)],
      oracles: [
        O('양손 물총', [K('물총', 1, 'oneAlly'), DRAW(1), SH(0.8)]),
        O('물풍선', [K('물총', 1, 'oneAlly'), DRAW(1), HL(0.8)]),
        O('기습 물총', [K('물총', 1, 'oneAlly'), DRAW(2)]),
        O('물놀이 초대장', [K('물총', 1, 'oneAlly'), DRAW(1), ST('결의', 1)], { tags: ['개전'] }),
        O('수문 앞 인사', [K('물총', 1, 'oneAlly'), DRAW(1), ST('탄성', 2)]),
      ],
      blesses: [B('젖은 머리', 'draw'), B('찰랑찰랑', 'guard'), BF('물방울 무늬', [HL(0.4)])] },
    { name: '수문 개방', type: '스킬', cost: 2, fx: [SH(2.0), HL(1.2), K('물총', 1, 'allAllies')],
      oracles: [
        up('대홍수', 1.35),
        cheap('작은 수문', 0.85),
        O('수문장의 방벽', [SH(2.4), ST('실드 유지', 1), K('물총', 1, 'allAllies')]),
        O('맑은 물길', [SH(2.0), HL(1.6), K('물총', 1, 'allAllies')], { tags: ['보존'] }),
        O('물의 축복', [SH(2.2), HL(1.4), K('물총', 1, 'allAllies')], { tags: ['축복'] }),
      ],
      blesses: [B('넘치는 물', 'heal'), B('굳센 둑', 'guard'), B('물살 타기', 'ap')] },
    { name: '물대포', type: '공격', cost: 1, fx: [D(1.2), K('물총', 1, 'oneAlly')],
      oracles: [
        up('고압 물대포', 1.4),
        O('물대포 연사', [D(0.5, E1, { hits: 3 }), K('물총', 1, 'oneAlly')]),
        O('흠뻑 젖어라', [D(1.2), ST('약화', 1, E1), K('물총', 1, 'oneAlly')]),
        O('물벼락', [D(0.9, EA), K('물총', 1, 'oneAlly')]),
        O('물수제비', [D(1.0), K('물총', 1, 'oneAlly')], { cost: 0 }),
      ],
      blesses: [B('세찬 물살', 'power'), B('차가운 물', 'frost'), B('가벼운 물통', 'cost')] },
    { name: '외로운 수문장', type: '강화', cost: 1, fx: [ST('탄성', 3), ST('결의', 1), K('물총', 1, 'allAllies')],
      oracles: [
        O('친구가 생겼어', [ST('탄성', 5), ST('결의', 1), K('물총', 1, 'allAllies')]),
        O('수문장 교대', [ST('탄성', 3), ST('결의', 1), K('물총', 1, 'allAllies')], { cost: 0 }),
        O('굳건한 수문', [ST('탄성', 3), ST('결의', 2), K('물총', 1, 'allAllies')]),
        O('물의 정령', [ST('탄성', 3), ST('결의', 1), ST('면역', 1)]),
        O('먼저 다가가기', [ST('탄성', 4), ST('결의', 1), K('물총', 1, 'allAllies')], { tags: ['개전'] }),
      ],
      blesses: [B('촉촉한 마음', 'defUp'), B('가벼운 발걸음', 'cost'), B('물장구', 'atkUp')] },
  ],
},
// ─────────────────────────────────────────────── 아일라
{
  hero: { id: '아일라', name: '아일라', nature: '순수', row: 'mid', role: '서포터', star: 3, hp: 660, atk: 86, def: 60, crit: 5,
    blurb: '화산섬의 정령. 맞을 때마다 빠직이 차오르고, 다섯이 차면 섬을 뒤엎는 대분화가 터진다 — 명상으로 식힐지, 터뜨릴지.',
    keyword: { name: '빠직', desc: '참고 있는 화 — 다섯이면 대분화', carrier: 'self', cap: 5,
      rules: [{ name: '대분화', when: { on: 'stackReach', id: '빠직', n: 5 }, fx: [D(2.0, EA), F('payHpPct', { v: 0.06 }), SP('빠직', 'all')] }] },
    passives: [
      { name: '부글부글', when: { on: 'hurt', guarded: true }, limit: { per: 'turn', n: 3 }, fx: [K('빠직', 1)] },
      { name: '명상', when: { on: 'play', type: '스킬' }, conds: [{ c: 'stack', id: '빠직', n: 1 }], limit: { per: 'turn', n: 2 }, fx: [SP('빠직', 1), HL(0.4)] },
    ],
    ult: { name: '활활화산', cost: 300, fx: [D(2.5, EA), ST('그을림', 5, EA), K('빠직', 2)] } },
  starters: [atk1('용암 방울'), hel('휴양지 온천')],
  uniques: [
    { name: '초폭망 직전', type: '스킬', cost: 0, fx: [K('빠직', 2), ST('그을림', 2, E1)],
      oracles: [
        O('폭망 단계 상승', [K('빠직', 3), ST('그을림', 3, E1)]),
        O('부글부글 끓기', [K('빠직', 2), ST('그을림', 2, EA)]),
        O('참을 만큼 참았어', [K('빠직', 2), ST('그을림', 2, E1), DRAW(1)]),
        O('김 빼기', [K('빠직', 2), ST('그을림', 2, E1), HL(0.6)]),
        O('화산재', [K('빠직', 2), ST('그을림', 2, E1), ST('약화', 1, E1)]),
      ],
      blesses: [B('들끓는 마그마', 'draw'), BF('뜨거운 숨', [ST('그을림', 1, E1)]), BT('화산 예보', ['개전'])] },
    { name: '용암 분출', type: '공격', cost: 2, fx: [D(1.2, EA), ST('그을림', 2, EA), K('빠직', 1)],
      oracles: [
        up('대용암류', 1.35),
        cheap('작은 분화구', 0.8),
        O('화쇄류', [D(1.4, EA), ST('그을림', 3, EA), K('빠직', 1)]),
        O('용암 기둥', [D(2.6), ST('그을림', 4, E1), K('빠직', 1)]),
        O('분노의 마그마', [D(1.2, EA), ST('그을림', 2, EA), K('빠직', 2)], { tags: ['보존'] }),
      ],
      blesses: [B('끓는 용암', 'power'), B('가벼운 화산탄', 'cost'), B('뜨거운 증기', 'weakSpot')] },
    { name: '명상 시간', type: '스킬', cost: 1, fx: [HL(0.8), F('perStack', { id: '빠직' }), HL(0.35), SP('빠직', 'all')],
      oracles: [
        O('깊은 명상', [HL(1.0), F('perStack', { id: '빠직' }), HL(0.45), SP('빠직', 'all')]),
        O('호흡 고르기', [HL(0.7), F('perStack', { id: '빠직' }), HL(0.3), SP('빠직', 'all')], { cost: 0 }),
        O('온천욕', [HL(0.8), F('perStack', { id: '빠직' }), SH(0.6), SP('빠직', 'all')], { tags: ['보존'] }),
        O('평정심', [HL(1.1), F('perStack', { id: '빠직' }), HL(0.35), SP('빠직', 'all')]),
        O('식은 용암', [SH(1.2), F('perStack', { id: '빠직' }), HL(0.4), SP('빠직', 'all')]),
      ],
      blesses: [B('따뜻한 물', 'heal'), B('명상 방석', 'cost'), B('한숨 돌리기', 'draw')] },
    { name: '화산섬의 주인', type: '강화', cost: 1, fx: [ST('불굴', 1), K('빠직', 2)],
      oracles: [
        O('화산섬의 여왕', [ST('불굴', 2), K('빠직', 2)]),
        O('잠든 화산', [ST('불굴', 1), K('빠직', 2)], { cost: 0 }),
        O('뜨거운 대지', [ST('불굴', 1), K('빠직', 2), ST('그을림', 3, EA)]),
        O('용암 갑옷', [ST('불굴', 1), K('빠직', 2), ST('결정화', 1)]),
        O('분화 준비', [ST('불굴', 1), K('빠직', 3)], { tags: ['개전'] }),
      ],
      blesses: [B('화산의 힘', 'atkUp'), B('용암 피부', 'defUp'), B('가벼운 분화', 'cost')] },
  ],
},
// ─────────────────────────────────────────────── 뮤트
{
  hero: { id: '뮤트', name: '뮤트', nature: '순수', row: 'back', role: '서포터', star: 3, hp: 500, atk: 86, def: 58, crit: 5,
    blurb: '나타와 뒤섞여 머릿속에서 늘 회의 중. 턴의 첫 카드가 공격이면 뮤트가, 스킬이면 나타가 그 턴 의장을 맡는다.',
    keywords: [
      { name: '뮤트 의장', desc: '이번 턴 회의는 뮤트가 이끈다 — 뮤트 카드가 적을 무르게 만든다', carrier: 'self', cap: 1, endClear: true,
        rules: [{ name: '뮤트 의장', when: { on: 'play', who: 'any', nth: 1, type: '공격' }, fx: [K('뮤트 의장', 1)] }] },
      { name: '나타 의장', desc: '이번 턴 회의는 나타가 이끈다 — 뮤트 카드가 파티를 지킨다', carrier: 'self', cap: 1, endClear: true,
        rules: [{ name: '나타 의장', when: { on: 'play', who: 'any', nth: 1, type: '스킬' }, fx: [K('나타 의장', 1)] }] },
    ],
    passives: [
      { name: '뮤트의 발언', when: { on: 'play' }, conds: [{ c: 'stack', id: '뮤트 의장', n: 1 }], fx: [ST('취약', 1, E1)] },
      { name: '나타의 발언', when: { on: 'play' }, conds: [{ c: 'stack', id: '나타 의장', n: 1 }], fx: [ST('피해 감소', 1)] },
    ],
    ult: { name: '기초적인 해킹', cost: 250, fx: [ST('취약', 2, EA), ST('피해 감소', 2), DRAW(2)] } },
  starters: [atk1('데이터 스트림'), hel('나타의 복구 코드')],
  uniques: [
    { name: '안건 상정', type: '스킬', cost: 0, fx: [DRAW(1), F('ifStack', { id: '뮤트 의장' }), ST('취약', 1, E1), F('ifStack', { id: '나타 의장' }), SH(1.0)],
      oracles: [
        O('긴급 안건', [DRAW(2), F('ifStack', { id: '뮤트 의장' }), ST('취약', 1, E1), F('ifStack', { id: '나타 의장' }), SH(1.0)]),
        O('강한 반대', [DRAW(1), F('ifStack', { id: '뮤트 의장' }), ST('취약', 2, E1), F('ifStack', { id: '나타 의장' }), SH(1.5)]),
        O('회의록', [DRAW(1), F('ifStack', { id: '뮤트 의장' }), ST('취약', 1, E1), F('ifStack', { id: '나타 의장' }), SH(1.0)], { tags: ['보존', '개전'] }),
        O('의사봉', [DRAW(1), F('ifStack', { id: '뮤트 의장' }), ST('취약', 1, EA), F('ifStack', { id: '나타 의장' }), SH(1.4)]),
        O('나타의 수정안', [DRAW(1), F('ifStack', { id: '뮤트 의장' }), ST('취약', 1, E1), F('ifStack', { id: '나타 의장' }), ST('피해 감소', 2)]),
      ],
      blesses: [B('빠른 결론', 'draw'), B('든든한 의견', 'guard'), BT('사전 협의', ['개전'])] },
    { name: '강제 종료', type: '공격', cost: 2, fx: [D(2.2), F('ifStack', { id: '뮤트 의장' }), ST('취약', 2, E1)],
      oracles: [
        up('전원 차단', 1.35),
        cheap('재부팅', 0.8),
        O('블루스크린', [D(2.4), ST('약화', 1, E1), F('ifStack', { id: '뮤트 의장' }), ST('취약', 2, E1)]),
        O('과부하', [D(1.4, EA), F('ifStack', { id: '뮤트 의장' }), ST('취약', 1, EA)]),
        O('작업 관리자', [D(2.2), F('ifStack', { id: '뮤트 의장' }), ST('취약', 2, E1), DRAW(1)], { tags: ['보존'] }),
      ],
      blesses: [B('강제 입력', 'power'), B('빠른 단축키', 'cost'), B('취약점 공략', 'weakSpot')] },
    { name: '방화벽', type: '스킬', cost: 1, fx: [SH(1.8), F('ifStack', { id: '나타 의장' }), ST('피해 감소', 2)],
      oracles: [
        up('이중 방화벽', 1.35),
        O('백신', [SH(1.8), F('cleanse', { v: 1 }), F('ifStack', { id: '나타 의장' }), ST('피해 감소', 2)]),
        O('복구 지점', [SH(1.8), HL(0.8), F('ifStack', { id: '나타 의장' }), ST('피해 감소', 2)]),
        O('보안 패치', [SH(1.6), F('ifStack', { id: '나타 의장' }), ST('피해 감소', 2)], { cost: 0 }),
        O('철벽 서버', [SH(2.0), ST('실드 유지', 1), F('ifStack', { id: '나타 의장' }), ST('피해 감소', 2)]),
      ],
      blesses: [B('튼튼한 코드', 'guard'), B('자동 저장', 'draw'), B('가벼운 패치', 'cost')] },
    { name: '만장일치', type: '강화', cost: 1, fx: [K('뮤트 의장', 1), K('나타 의장', 1), ST('사기', 1)],
      oracles: [
        O('완벽한 합의', [K('뮤트 의장', 1), K('나타 의장', 1), ST('사기', 2)]),
        O('빠른 표결', [K('뮤트 의장', 1), K('나타 의장', 1), ST('사기', 1)], { cost: 0 }),
        O('두 자아의 화해', [K('뮤트 의장', 1), K('나타 의장', 1), ST('면역', 2)]),
        O('합동 연설', [K('뮤트 의장', 1), ST('사기', 1), ST('취약', 2, EA)]),
        O('첫 안건', [K('뮤트 의장', 1), K('나타 의장', 1), ST('사기', 1)], { tags: ['개막'] }),
      ],
      blesses: [B('날카로운 논리', 'atkUp'), B('차분한 목소리', 'defUp'), B('짧은 회의', 'cost')] },
  ],
},
// ─────────────────────────────────────────────── 빅우드
{
  hero: { id: '빅우드', name: '빅우드', nature: '순수', row: 'front', role: '탱커', star: 2, hp: 930, atk: 66, def: 61, crit: 5,
    blurb: '얻어맞으면서도 웃는 나무 정령. 맞을 때마다 나이테가 늘고, 나이테가 두꺼울수록 그가 거는 실드도 두꺼워진다.',
    keyword: { name: '나이테', desc: '맞으며 늘어난 나이테 — 쌓일수록 실드가 두꺼워진다', carrier: 'self', cap: 5, per: [{ stat: 'guard', v: 0.1 }] },
    passives: [
      { name: '거기 말고 여기', when: { on: 'hurt', guarded: true }, limit: { per: 'turn', n: 3 }, fx: [K('나이테', 1)] },
      { name: '오래된 나무', when: { on: 'play' }, conds: [{ c: 'stack', id: '나이테', n: 5 }], fx: [ST('결정화', 2), SP('나이테', 'all')] },
    ],
    ult: { name: '나를~ 바라 봐라~', cost: 250, fx: [SH(3.0), ST('피해 감소', 2), K('나이테', 2)] } },
  starters: [atk1('나뭇가지 후려치기'), shd('나무껍질')],
  uniques: [
    { name: '뿌리 내리기', type: '스킬', cost: 1, signature: true, fx: [SH(2.0), K('나이테', 1), ST('반격', 1)],
      oracles: [
        up('깊은 뿌리', 1.35),
        O('얽힌 뿌리', [SH(2.0), K('나이테', 1), ST('반격', 2)]),
        O('굵은 줄기', [SH(2.4), K('나이테', 2), ST('반격', 1)]),
        O('잔뿌리', [SH(1.6), K('나이테', 1), ST('반격', 1)], { cost: 0 }),
        keep('천년 뿌리', 1.25),
      ],
      blesses: [B('단단한 껍질', 'guard'), B('수액', 'heal'), B('새싹', 'draw')] },
    { name: '나이테 세기', type: '스킬', cost: 1, fx: [F('perStack', { id: '나이테' }), HL(0.4), ST('결정화', 1)],
      oracles: [
        O('나이테 자랑', [F('perStack', { id: '나이테' }), HL(0.55), ST('결정화', 1)]),
        O('한 줄씩', [F('perStack', { id: '나이테' }), HL(0.35), ST('결정화', 1)], { cost: 0 }),
        O('수액 흘리기', [F('perStack', { id: '나이테' }), HL(0.4), ST('결정화', 2)]),
        O('나이테 방패', [F('perStack', { id: '나이테' }), SH(0.6), ST('결정화', 1)]),
        O('잊지 않는 나무', [F('perStack', { id: '나이테' }), HL(0.4), ST('결정화', 1)], { tags: ['보존', '축복'] }),
      ],
      blesses: [B('푸른 잎', 'heal'), B('가벼운 가지', 'cost'), BF('송진', [SH(0.5)])] },
    { name: '통나무 굴리기', type: '공격', cost: 2, fx: [DD(0.9, EA), SH(1.0)],
      oracles: [
        up('거목 굴리기', 1.35),
        cheap('나뭇단 굴리기', 0.8),
        O('뿌리째 뽑기', [DD(1.0, EA), SH(1.0), ST('약화', 1, EA)]),
        O('통나무 찍기', [DD(1.8), SH(1.2), TOUGH(1)]),
        O('나이테 굴리기', [DD(0.9, EA), SH(1.0), K('나이테', 2)]),
      ],
      blesses: [B('묵직한 통나무', 'power'), B('미끄러운 비탈', 'cost'), B('도토리 세례', 'frost')] },
    { name: '숲의 품', type: '강화', cost: 1, fx: [ST('결정화', 2), K('나이테', 2)],
      oracles: [
        O('깊은 숲', [ST('결정화', 3), K('나이테', 2)]),
        O('작은 숲', [ST('결정화', 2), K('나이테', 2)], { cost: 0 }),
        O('숲의 파수꾼', [ST('결정화', 2), K('나이테', 2), ST('반격', 2)]),
        O('나무 그늘', [ST('결정화', 2), K('나이테', 2), ST('불굴', 1)]),
        O('먼저 자란 나무', [ST('결정화', 2), K('나이테', 3)], { tags: ['개전'] }),
      ],
      blesses: [B('뿌리 깊은 힘', 'defUp'), B('가지 휘두르기', 'atkUp'), B('씨앗', 'cost')] },
  ],
},
// ─────────────────────────────────────────────── 가비아
{
  hero: { id: '가비아', name: '가비아', nature: '순수', row: 'mid', role: '서포터', star: 2, hp: 640, atk: 64, def: 63, crit: 5,
    blurb: '목소리를 키우면 땅이 울리는 대지의 정령. 카드를 속삭임으로 낼지 외침으로 낼지 고른다 — 외침은 두 배지만 목청이 차오른다.',
    keyword: { name: '목청', desc: '외치고 난 목 — 외침을 고르면 차고, 땅이 울리지만 손이 미끄러진다', carrier: 'self', cap: 1,
      rules: [{ name: '지진', when: { on: 'stackReach', id: '목청', n: 1 }, fx: [TOUGH(1, EA), ST('미끄러움', 1, 'party'), SP('목청', 'all')] }] },
    passives: [
      { name: '조용한 대지', when: { on: 'turnEnd' }, conds: [{ c: 'ownNone' }], fx: [SH(1.0)] },
    ],
    ult: { name: '지켜⋯줄⋯게⋯', cost: 150, fx: [SH(2.5), ST('불굴', 1), TOUGH(1, EA)] } },
  starters: [atk1('돌멩이…'), hel('토닥…')],
  uniques: [
    { name: '작은 목소리', type: '스킬', cost: 1, choices: ['속삭임', '외침'], fx: [F('ifChoice', { n: 1 }), SH(1.6), F('ifChoice', { n: 2 }), SH(3.2), K('목청', 1)],
      oracles: [
        O('또렷한 목소리', [F('ifChoice', { n: 1 }), SH(2.0), F('ifChoice', { n: 2 }), SH(4.0), K('목청', 1)]),
        O('귓속말', [F('ifChoice', { n: 1 }), SH(1.4), F('ifChoice', { n: 2 }), SH(2.8), K('목청', 1)], { cost: 0 }),
        O('바위 같은 목소리', [F('ifChoice', { n: 1 }), ST('불굴', 1), F('ifChoice', { n: 2 }), SH(3.6), K('목청', 1)]),
        O('지켜 줄게', [F('ifChoice', { n: 1 }), SH(1.8), F('ifChoice', { n: 2 }), SH(3.6), K('목청', 1)], { tags: ['보존'] }),
        O('최애를 향한 외침', [F('ifChoice', { n: 1 }), SH(1.6), F('ifChoice', { n: 2 }), SH(3.2), ST('사기', 1)]),
      ],
      blesses: [B('단단한 바위', 'guard'), B('한숨', 'draw'), B('가벼운 숨', 'cost')] },
    { name: '돌멩이 던지기', type: '공격', cost: 1, choices: ['속삭임', '외침'], fx: [F('ifChoice', { n: 1 }), D(1.3), F('ifChoice', { n: 2 }), D(2.6), K('목청', 1)],
      oracles: [
        O('큰 돌멩이', [F('ifChoice', { n: 1 }), D(1.6), F('ifChoice', { n: 2 }), D(3.2), K('목청', 1)]),
        O('조약돌', [F('ifChoice', { n: 1 }), D(1.1), F('ifChoice', { n: 2 }), D(2.2), K('목청', 1)], { cost: 0 }),
        O('바위 굴리기', [F('ifChoice', { n: 1 }), D(0.9, EA), F('ifChoice', { n: 2 }), D(1.8, EA), K('목청', 1)]),
        O('정확한 투척', [F('ifChoice', { n: 1 }), D(1.4), F('ifChoice', { n: 2 }), D(2.8), K('목청', 1)], { tags: ['약점 공격'] }),
        O('던지고 숨기', [F('ifChoice', { n: 1 }), D(1.4), F('ifChoice', { n: 2 }), D(2.8), K('목청', 1)], { tags: ['보존'] }),
      ],
      blesses: [B('묵직한 돌', 'power'), B('가벼운 조약돌', 'cost'), B('모래 뿌리기', 'frost')] },
    { name: '토닥토닥', type: '스킬', cost: 1, choices: ['속삭임', '외침'], fx: [F('ifChoice', { n: 1 }), HL(1.2), F('ifChoice', { n: 2 }), HL(2.4), K('목청', 1)],
      oracles: [
        O('꼭 안아 주기', [F('ifChoice', { n: 1 }), HL(1.5), F('ifChoice', { n: 2 }), HL(3.0), K('목청', 1)]),
        O('살짝 토닥', [F('ifChoice', { n: 1 }), HL(1.0), F('ifChoice', { n: 2 }), HL(2.0), K('목청', 1)], { cost: 0 }),
        O('괜찮아', [F('ifChoice', { n: 1 }), HL(1.4), F('ifChoice', { n: 2 }), HL(2.8), K('목청', 1)], { tags: ['개전'] }),
        O('대지의 온기', [F('ifChoice', { n: 1 }), SH(1.8), F('ifChoice', { n: 2 }), HL(2.8), K('목청', 1)]),
        O('자장가', [F('ifChoice', { n: 1 }), HL(1.4), F('ifChoice', { n: 2 }), HL(2.8), K('목청', 1)], { tags: ['축복'] }),
      ],
      blesses: [B('따뜻한 손', 'heal'), B('작은 손', 'cost'), B('포근한 흙', 'guard')] },
    { name: '목청 가다듬기', type: '스킬', cost: 0, choices: ['속삭임', '외침'], fx: [F('ifChoice', { n: 1 }), DRAW(1), F('ifChoice', { n: 2 }), DRAW(2), K('목청', 1)],
      oracles: [
        O('발성 연습', [F('ifChoice', { n: 1 }), DRAW(2), F('ifChoice', { n: 2 }), DRAW(3), K('목청', 1)]),
        O('물 한 모금', [F('ifChoice', { n: 1 }), HL(1.0), F('ifChoice', { n: 2 }), DRAW(3), K('목청', 1)]),
        O('준비 운동', [F('ifChoice', { n: 1 }), DRAW(1), F('ifChoice', { n: 2 }), DRAW(2), K('목청', 1)], { tags: ['개전'] }),
        O('깊은 숨', [F('ifChoice', { n: 1 }), DRAW(2), F('ifChoice', { n: 2 }), DRAW(3), K('목청', 1)]),
        O('응원 연습', [F('ifChoice', { n: 1 }), DRAW(1), F('ifChoice', { n: 2 }), DRAW(2), ST('사기', 1)]),
      ],
      blesses: [B('맑은 목', 'draw'), B('한 걸음 더', 'ap'), BT('목 풀기', ['개전'])] },
  ],
},
// ─────────────────────────────────────────────── 우이(기억)
{
  hero: { id: '우이_기억', name: '우이(기억)', nature: '냉정', row: 'back', role: '서포터', star: 3, hp: 580, atk: 95, def: 61, crit: 5,
    blurb: '지웠던 불행한 기억을 안고 돌아온 본체. 카드가 소멸할 때마다 되찾은 기억이 쌓여 손끝이 단단해지고, 제 카드가 사라질 땐 파티의 아픔 하나를 씻어 낸다.',
    keyword: { name: '되찾은 기억', desc: '사라진 카드에서 건져 올린 기억', carrier: 'self', cap: 6,
      per: [{ stat: 'dealt', v: 0.1 }, { stat: 'guard', v: 0.1 }] },
    passives: [
      { name: '도망치지 않는 기억', when: { on: 'exhaust', who: 'any' }, limit: { per: 'turn', n: 3 }, fx: [K('되찾은 기억', 1)] },
      { name: '씻겨 가는 아픔', when: { on: 'exhaust' }, limit: { per: 'turn', n: 2 }, fx: [F('cleanse', { v: 1 })] },
    ],
    ult: { name: '이젠 피하지 않아', cost: 200, fx: [F('pull', { from: 'gone', at: 'random', n: 1 }), HL(1.5), K('되찾은 기억', 2)] } },
  starters: [atk1('물방울'), hel('맑은 연못물')],
  uniques: [
    { name: '잊으려던 기억', type: '스킬', cost: 0, tags: ['소멸'], fx: [DRAW(2), K('되찾은 기억', 1)],
      oracles: [
        O('선명한 기억', [DRAW(2), K('되찾은 기억', 2)], { tags: ['소멸'] }),
        O('기억의 파편', [DRAW(2), K('되찾은 기억', 1), SH(0.8)], { tags: ['소멸'] }),
        O('되감기', [DRAW(2), K('되찾은 기억', 1), HL(0.6)], { tags: ['소멸'] }),
        O('놓지 않아', [DRAW(2), K('되찾은 기억', 1)], { tags: ['소멸 2'] }),
        O('첫 기억', [DRAW(3), K('되찾은 기억', 1)], { tags: ['소멸', '개전'] }),
      ],
      blesses: [B('또렷한 눈', 'draw'), B('물결', 'ap'), BT('기억 상자', ['개전'])] },
    { name: '기억의 물결', type: '공격', cost: 1, fx: [D(1.0), F('perPile', { from: 'gone' }), D(0.12)],
      oracles: [
        O('밀려오는 기억', [D(1.2), F('perPile', { from: 'gone' }), D(0.15)]),
        O('잔물결', [D(0.8), F('perPile', { from: 'gone' }), D(0.1)], { cost: 0 }),
        O('기억의 해일', [D(0.7, EA), F('perPile', { from: 'gone' }), D(0.08, EA)]),
        O('흘려보내기', [D(1.0), F('perPile', { from: 'gone' }), D(0.12), DRAW(1)]),
        O('마주 보기', [D(1.1), F('perPile', { from: 'gone' }), D(0.12), ST('약화', 1, E1)]),
      ],
      blesses: [B('거센 물결', 'power'), B('얕은 물', 'cost'), B('차가운 기억', 'frost')] },
    { name: '떠나보내기', type: '스킬', cost: 1, fx: [F('burn', { v: 1 }), SH(1.6), DRAW(1)],
      oracles: [
        up('담담한 작별', 1.35),
        O('가벼워진 마음', [F('burn', { v: 1 }), SH(1.4), DRAW(1)], { cost: 0 }),
        O('정리하기', [F('burn', { v: 2 }), SH(1.8), DRAW(2)]),
        O('작별 인사', [F('burn', { v: 1 }), SH(1.6), HL(1.0)]),
        O('기억으로 남기', [F('burn', { v: 1 }), SH(1.6), K('되찾은 기억', 2)]),
      ],
      blesses: [B('단단한 마음', 'guard'), B('빈손', 'draw'), B('가벼운 몸', 'cost')] },
    { name: '다시 마주한 기억', type: '스킬', cost: 1, tags: ['소멸'], fx: [F('pull', { from: 'gone', at: 'random', n: 1 }), HL(0.8)],
      oracles: [
        O('두 번째 기회', [F('pull', { from: 'gone', at: 'random', n: 1 }), HL(1.2), DRAW(1)], { tags: ['소멸'] }),
        O('되돌아온 날', [F('pull', { from: 'gone', at: 'random', n: 1 }), HL(0.6)], { cost: 0, tags: ['소멸'] }),
        O('기억 꺼내기', [F('pull', { from: 'gone', at: 'random', n: 2 }), HL(0.8)], { tags: ['소멸'] }),
        O('본체의 귀환', [F('pull', { from: 'gone', at: 'random', n: 1 }), HL(0.8), K('되찾은 기억', 2)], { tags: ['소멸'] }),
        O('품에 안기', [F('pull', { from: 'gone', at: 'random', n: 1 }), SH(1.4), HL(0.8)], { tags: ['소멸'] }),
      ],
      blesses: [B('맑은 연못', 'heal'), B('젖은 발', 'cost'), B('기억 한 줌', 'draw')] },
  ],
},
// ─────────────────────────────────────────────── 니콜
{
  hero: { id: '니콜', name: '니콜', nature: '냉정', row: 'back', role: '딜러', star: 3, hp: 500, atk: 145, def: 25, crit: 10,
    blurb: '완벽을 강요하는 감독. 고유 카드는 내고 나면 손으로 돌아와 테이크를 쌓고, 세 번째 테이크에 「오케이 컷」 이 나온다.',
    keyword: { name: '테이크', desc: '다시 찍은 횟수 — 쌓일수록 세지고, 셋이면 「오케이 컷」', carrier: 'self', cap: 3, per: [{ stat: 'dealt', v: 0.15 }],
      rules: [{ name: '오케이 컷', when: { on: 'stackReach', id: '테이크', n: 3 }, fx: [SP('테이크', 'all'), F('make', { id: '니콜_t1', v: 1 })] }] },
    passives: [
      { name: '한 번 더 갑니다', when: { on: 'play', type: '공격' }, limit: { per: 'turn', n: 1 }, fx: [K('테이크', 1)] },
    ],
    ult: { name: '바삭 바삭 재촬영 파이어', cost: 250, fx: [D(0.8, EA, { hits: 2 }), K('테이크', 2)] } },
  starters: [atk1('팝콘 투척'), atk2('팝콘 버킷 투척'), shd('슬레이트 막기', 1)],
  tokens: [{ id: '니콜_t1', name: '오케이 컷', cost: 0, type: '공격', tags: ['소멸'], fx: [D(1.4, EA), ST('취약', 1, EA)], blurb: '필름을 태우며 외치는 완벽한 한 컷.' }],
  uniques: [
    { name: '액션!', type: '공격', cost: 1, tags: ['회수'], signature: true, fx: [D(1.1), K('테이크', 1)],
      oracles: [
        up('롱테이크', 1.35),
        O('클로즈업', [D(1.4), TOUGH(1), K('테이크', 1)], { tags: ['회수'] }),
        O('컷 나누기', [D(0.55, E1, { hits: 3 }), K('테이크', 1)], { tags: ['회수'] }),
        O('연속 촬영', [D(1.1), K('테이크', 1)], { tags: ['회수 3'] }),
        O('리허설', [D(0.9), K('테이크', 1)], { cost: 0, tags: ['회수'] }),
      ],
      blesses: [B('완벽한 각도', 'power'), B('빠른 세팅', 'cost'), B('조명 직격', 'weakSpot')] },
    { name: '다시 갑니다', type: '공격', cost: 1, tags: ['회수'], fx: [D(0.55, E1, { hits: 2 }), K('테이크', 1)],
      oracles: [
        up('한 번 더 갑니다', 1.35),
        O('스턴트', [D(0.55, EA, { hits: 2 }), K('테이크', 1)], { cost: 2, tags: ['회수'] }),
        O('NG 모음', [D(0.4, ER, { hits: 4 }), K('테이크', 1)], { tags: ['회수'] }),
        O('카메라 리허설', [D(0.5, E1, { hits: 2 }), K('테이크', 1)], { cost: 0, tags: ['회수'] }),
        O('감독의 시범', [D(0.6, E1, { hits: 2 }), K('테이크', 1), DRAW(1)], { tags: ['회수'] }),
      ],
      blesses: [B('불꽃 연출', 'power'), B('촬영장 질주', 'cost'), B('조명 반사', 'frost')] },
    { name: 'NG 컷', type: '스킬', cost: 0, tags: ['회수'], fx: [K('테이크', 1), DRAW(1)],
      oracles: [
        O('필름 갈기', [K('테이크', 1), DRAW(2)], { tags: ['회수'] }),
        O('슬레이트 치기', [K('테이크', 1), DRAW(1), SH(1.0)], { tags: ['회수'] }),
        O('모니터 확인', [K('테이크', 2), DRAW(1)], { tags: ['회수'] }),
        O('컷 사인', [K('테이크', 1), DRAW(1), ST('사기', 1)], { tags: ['회수'] }),
        O('콘티 수정', [K('테이크', 1), DRAW(1)], { tags: ['회수 3'] }),
      ],
      blesses: [B('빠른 손', 'draw'), B('발맞추기', 'ap'), BF('확성기', [ST('취약', 1, E1)])] },
    { name: '감독의 고집', type: '강화', cost: 1, fx: [K('테이크', 2), F('atkMod', { v: 0.2, run: true, target: 'self' })],
      oracles: [
        O('32테이크', [K('테이크', 2), F('atkMod', { v: 0.3, run: true, target: 'self' })]),
        O('촬영 개시', [K('테이크', 2), F('atkMod', { v: 0.2, run: true, target: 'self' })], { cost: 0 }),
        O('완벽주의', [K('테이크', 2), F('atkMod', { v: 0.2, run: true, target: 'self' }), F('critMod', { v: 0.1, run: true, target: 'self' })]),
        O('필름 태우기', [K('테이크', 2), F('atkMod', { v: 0.2, run: true, target: 'self' }), DRAW(2)]),
        O('오프닝 크레딧', [K('테이크', 2), F('atkMod', { v: 0.25, run: true, target: 'self' })], { tags: ['개전'] }),
      ],
      blesses: [B('명감독', 'atkUp'), B('짧은 회의', 'cost'), B('감독 의자', 'defUp')] },
  ],
},
// ─────────────────────────────────────────────── 실라
{
  hero: { id: '실라', name: '실라', nature: '냉정', row: 'back', role: '딜러', star: 3, hp: 550, atk: 145, def: 25, crit: 10,
    blurb: '정면 승부엔 강하고 기습엔 약한 바람의 맏언니. 한 적을 정면으로 마주 보고 쏠수록 그 적은 바람에 깎여 무너진다.',
    keyword: { name: '정면 승부', desc: '실라와 정면으로 마주 선 적', carrier: 'enemy', cap: 3, hunt: true, per: [{ stat: 'taken', v: 0.1 }] },
    passives: [
      { name: '맞바람', when: { on: 'play', type: '공격' }, fx: [K('정면 승부', 1, E1)] },
      { name: '기습엔 약해', when: { on: 'hurt', guarded: true }, conds: [{ c: 'firstTurn' }], limit: { per: 'fight', n: 1 }, fx: [ST('둔화', 1, E1)] },
    ],
    ult: { name: '헥토파스칼 스윙!', cost: 150, fx: [D(2.5), ST('둔화', 2, E1), TOUGH(2)] } },
  starters: [atk1('화살'), atk2('돌풍 화살'), shd('바람막이', 1)],
  uniques: [
    { name: '정조준', type: '공격', cost: 1, signature: true, fx: [D(1.3), F('ifFoe', { id: 'attack' }), D(0.65), ST('둔화', 1, E1)],
      oracles: [
        O('흔들림 없는 시위', [D(1.6), F('ifFoe', { id: 'attack' }), D(0.8), ST('둔화', 1, E1)]),
        O('맞받아 쏘기', [D(1.3), F('ifFoe', { id: 'attack' }), D(0.9), ST('둔화', 2, E1)]),
        O('바람 가르기', [D(1.3), TOUGH(1), F('ifFoe', { id: 'attack' }), D(0.65)]),
        O('속사', [D(1.0), F('ifFoe', { id: 'attack' }), D(0.5), ST('둔화', 1, E1)], { cost: 0 }),
        O('겨눠 두기', [D(1.4), F('ifFoe', { id: 'attack' }), D(0.7), ST('둔화', 1, E1)], { tags: ['보존'] }),
      ],
      blesses: [B('강한 활시위', 'power'), B('빠른 손', 'cost'), B('급소 조준', 'weakSpot')] },
    { name: '돌풍 연사', type: '공격', cost: 2, fx: [D(0.6, E1, { hits: 4 }), K('정면 승부', 1, E1)],
      oracles: [
        up('폭풍 연사', 1.35),
        cheap('산들바람 연사', 0.8),
        O('소용돌이 화살', [D(0.45, ER, { hits: 6 }), K('정면 승부', 1, E1)]),
        O('관통 화살', [D(0.65, E1, { hits: 4 }), K('정면 승부', 1, E1)], { tags: ['분쇄'] }),
        O('바람의 길', [D(0.6, E1, { hits: 4 }), K('정면 승부', 2, E1), ST('둔화', 1, E1)]),
      ],
      blesses: [B('거센 바람', 'power'), B('순풍', 'cost'), B('찬바람', 'frost')] },
    { name: '바람 읽기', type: '스킬', cost: 0, fx: [ST('둔화', 1, E1), K('정면 승부', 1, E1), DRAW(1)],
      oracles: [
        O('기류 파악', [ST('둔화', 1, E1), K('정면 승부', 2, E1), DRAW(1)]),
        O('바람막이 세우기', [ST('둔화', 1, E1), K('정면 승부', 1, E1), SH(1.0)]),
        O('맏언니의 눈', [ST('둔화', 2, E1), K('정면 승부', 1, E1), DRAW(1)]),
        O('먼저 보기', [ST('둔화', 1, E1), K('정면 승부', 1, E1), DRAW(1)], { tags: ['개전'] }),
        O('정면에서', [ST('취약', 1, E1), K('정면 승부', 1, E1), DRAW(1)]),
      ],
      blesses: [B('날카로운 눈', 'draw'), B('바람 타기', 'ap'), BF('겨눈 화살', [ST('둔화', 1, E1)])] },
    { name: '맏언니의 각오', type: '강화', cost: 1, fx: [F('atkMod', { v: 0.2, run: true, target: 'self' }), ST('잔광', 2)],
      oracles: [
        O('물러서지 않아', [F('atkMod', { v: 0.3, run: true, target: 'self' }), ST('잔광', 2)]),
        O('가벼운 각오', [F('atkMod', { v: 0.2, run: true, target: 'self' }), ST('잔광', 2)], { cost: 0 }),
        O('바람의 수호', [F('atkMod', { v: 0.2, run: true, target: 'self' }), ST('잔광', 2), ST('피해 감소', 2)]),
        O('정면 돌파', [F('atkMod', { v: 0.2, run: true, target: 'self' }), ST('잔광', 3)]),
        O('먼저 일어선 언니', [F('atkMod', { v: 0.25, run: true, target: 'self' }), ST('잔광', 2)], { tags: ['개전'] }),
      ],
      blesses: [B('굳센 팔', 'atkUp'), B('바람 망토', 'defUp'), B('가벼운 화살통', 'cost')] },
  ],
},
// ─────────────────────────────────────────────── 잉클
{
  hero: { id: '잉클', name: '잉클', nature: '냉정', row: 'back', role: '딜러', star: 3, hp: 550, atk: 145, def: 25, crit: 10,
    blurb: '세상에 한 획 긋기가 소원인 먹물 정령. 공격할 때마다 적 전체에 먹이 번지고, 스킬로 번진 먹을 한 획에 긋는다.',
    keyword: { name: '번짐', desc: '적에게 스며든 먹물', carrier: 'enemy', cap: 5, per: [{ stat: 'taken', v: 0.05 }] },
    passives: [
      { name: '먹물 튀기기', when: { on: 'play', type: '공격' }, fx: [K('번짐', 1, EA)] },
    ],
    ult: { name: '한 폭 수묵화', cost: 200, fx: [K('번짐', 3, EA), D(1.5, EA)] } },
  starters: [atk1('붓끝 찌르기'), atk2('큰붓 내려긋기'), shd('먹 번짐 가림막', 1)],
  uniques: [
    { name: '세상에 한 획', type: '스킬', cost: 1, signature: true, fx: [F('perStack', { id: '번짐' }), D(0.4), SP('번짐', 2)],
      oracles: [
        O('굵은 한 획', [F('perStack', { id: '번짐' }), D(0.55), SP('번짐', 2)]),
        O('가는 한 획', [F('perStack', { id: '번짐' }), D(0.35), SP('번짐', 2)], { cost: 0 }),
        O('번지지 않는 먹', [F('perStack', { id: '번짐' }), D(0.4), SP('번짐', 1)]),
        O('획 그리고 점', [F('perStack', { id: '번짐' }), D(0.4), SP('번짐', 2), DRAW(1)]),
        O('붓 세우기', [F('perStack', { id: '번짐' }), D(0.45), SP('번짐', 2)], { tags: ['보존'] }),
      ],
      blesses: [B('붓놀림', 'draw'), B('가벼운 붓', 'cost'), BF('먹 한 방울', [K('번짐', 1, E1)])] },
    { name: '큰 붓 휘두르기', type: '공격', cost: 2, fx: [D(1.2, EA), K('번짐', 1, EA)],
      oracles: [
        up('대필', 1.35),
        cheap('잔붓질', 0.8),
        O('먹구름', [D(1.2, EA), K('번짐', 2, EA)]),
        O('발묵', [D(1.1, EA), K('번짐', 1, EA), ST('취약', 1, EA)]),
        O('파묵', [D(2.6), K('번짐', 2, E1)]),
      ],
      blesses: [B('힘찬 획', 'power'), B('붓 바꾸기', 'cost'), B('스며드는 먹', 'weakSpot')] },
    { name: '농담 조절', type: '스킬', cost: 0, fx: [K('번짐', 2, E1), DRAW(1)],
      oracles: [
        O('진한 먹', [K('번짐', 3, E1), DRAW(1)]),
        O('먹 갈기', [K('번짐', 2, E1), DRAW(2)]),
        O('흩뿌리기', [K('번짐', 1, EA), DRAW(1)]),
        O('화선지 깔기', [K('번짐', 2, E1), DRAW(1), SH(0.8)]),
        O('밑그림', [K('번짐', 2, E1), DRAW(1)], { tags: ['개전'] }),
      ],
      blesses: [B('먹물 튀김', 'draw'), B('벼루', 'ap'), BF('번지는 먹', [K('번짐', 1, E1)])] },
    { name: '먹물 정령의 소원', type: '강화', cost: 1, fx: [ST('취약', 1, EA), K('번짐', 2, EA)],
      oracles: [
        O('한 폭의 세상', [ST('취약', 2, EA), K('번짐', 2, EA)]),
        O('먹 한 점', [ST('취약', 1, EA), K('번짐', 2, EA)], { cost: 0 }),
        O('붓을 든 손', [ST('취약', 1, EA), K('번짐', 2, EA), F('atkMod', { v: 0.15, run: true, target: 'self' })]),
        O('넓은 화선지', [ST('취약', 1, EA), K('번짐', 3, EA)]),
        O('첫 획', [ST('취약', 1, EA), K('번짐', 2, EA)], { tags: ['개막'] }),
      ],
      blesses: [B('먹의 무게', 'atkUp'), B('고요한 마음', 'defUp'), B('짧은 붓', 'cost')] },
  ],
},
];
