// 적 수 · 패시브 · 쌓이는 수치 짓는 도우미
const X = (o, e) => Object.assign(o, e || {});
module.exports = {
  A: (v, say, e) => X({ t: "attack", v, say }, e),
  B: (v, say, e) => X({ t: "back", v, say }, e),
  M: (v, n, say, e) => X({ t: "multi", v, n, say }, e),
  AA: (v, say, e) => X({ t: "attackAll", v, say }, e),
  BL: (v, say, e) => X({ t: "block", v, say }, e),
  G: (v, say, e) => X({ t: "guard", v, say }, e),
  H: (v, say, e) => X({ t: "heal", v, say }, e),
  BF: (id, v, say, e) => X({ t: "buff", id, v, say }, e),
  BFA: (id, v, say, e) => X({ t: "buff", id, v, say, all: true }, e),
  DB: (id, v, say, e) => X({ t: "debuff", id, v, say }, e),
  J: (v, say, e) => X({ t: "jam", v, say }, e),
  AC: (id, n, to, say, e) => X({ t: "addCard", id, n, to, say }, e),
  CD: (id, n, to, say, e) => X({ t: "cardDebuff", id, n, to, say }, e),
  HC: (v, n, say, e) => X({ t: "handCost", v, n, say }, e),
  SM: (id, n, max, say, e) => X({ t: "summon", id, n, max, say }, e),
  CT: (id, v, say, e) => X({ t: "count", id, v, say }, e),
  SH: (next, say) => ({ t: "shift", next, say }),
  CH: (say, next, brk, e) => X(brk ? { t: "charge", say, next, brk: true } : { t: "charge", say, next }, e),
  RS: (id, n, say) => ({ t: "reshuffle", id, n, say }),
  AP: (n, say) => ({ t: "autoPlay", n, say }),
  TH: (v, say) => ({ t: "thorns", v, say }),
  SHL: (v, say) => ({ t: "selfHeal", v, say }),
  RV: (v, n, say) => ({ t: "revive", v, n, say }),
  FG: (say) => ({ t: "feign", say }),
  P: (name, on, d, e) => X({ name, on, do: d }, e),
  C: (o) => o,
};
